# Generated by Django 4.1.6 on 2023-02-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="Email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="Password",
            new_name="password",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="Username",
            new_name="username",
        ),
    ]
