# Generated by Django 4.1.6 on 2023-02-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_email_client_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("music", models.FileField(upload_to="media")),
            ],
        ),
    ]
